sudo: required 
language: generic
script: 
  - docker run -e CI=true nd_do/react-docker-app npm run test 
services:
  - docker
before_install:
  - docker build -t nd_do/react-docker-app -f Dockerfile.dev .
